package com.rexru.cheeseburgernocheese;

/*
 * Created by Rexru101 on 5/2/2015.
 */
public enum OrderAbility
{
    TRADE_DOWN,
    OPPONENT_TRASH_HAND,
    USE_INGREDIENT_FOR_ORDER,
    REPLACE_ACTIVE_ORDERS,
    TRASH_HAND,
    SHUFFLE_PLAYERS_HANDS,
    REVIVE_TOP_OF_TRASH,
    TRADE_TWICE,
    TAKE_CARD_FROM_OPPONENT,
    TWO_TURNS,
    REVIVE,
    REPLACE_ACTIVE_ORDERS_FAST,
    PREVENT_ORDER_ABILITY,
    OPPONENT_TRASH_HAND_FAST,//ends their turn
    SWAP_ORDER,
    TRASH_EVERYTHING_FAST,//hands, store
    OPPONENT_TRASH_ORDER,
    NONE;
}
